### PR TITLE
[server] fix #201 allowing multiple Results item.run

### LINKED ISSUE #201: Multiple Results still brake
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/lib/timeside/timeside/server/tasks.py", line 39, in experience_run
    item.run(experience)
  File "/srv/lib/timeside/timeside/server/models.py", line 600, in run
    set_results_from_processor(proc, preset)
  File "/srv/lib/timeside/timeside/server/models.py", line 560, in set_results_from_processor
    item=self
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
timeside.server.models.Result.MultipleObjectsReturned: get() returned more than one Result -- it returned 2!

### PR DESCRIPTION
**Pull request by Tointoin**
Hi @yomguy  and @gnuletik. I don't know what raised [#201](https://github.com/Parisson/TimeSide/issues/202) but this may be a quick fix.

### CODE REVIEW

**Comment by gnuletik** [comment]
Thanks a lot for looking into this @Tointoin !

That would help but it seems that this workaround would not fix the underlying problem because we would still have duplicate results in DB. I'd rather like to find where are those duplicates results created.

**Comment by Tointoin** [comment]
> I'd rather like to find where are those duplicates results created.

Occurrence of duplicate results may be caused by this [`get_result` function](https://github.com/Parisson/TimeSide/blob/8ca0c3e79a482ff338b0ed126e5a0a7949c01e58/timeside/server/utils.py#L52).

It is used [in `AnalysisTrackSerializer`](https://github.com/Parisson/TimeSide/blob/8ca0c3e79a482ff338b0ed126e5a0a7949c01e58/timeside/server/serializers.py#L739) to get result's uuid and url.

Problem is that Task running cannot return the created result because many cases are possible: 1 task running can resulting several results for several presets and items.

**Comment by gnuletik** [comment]
Thanks for the details ! I can see it more clearly now.
I'm also creating Task through the script that I rewrote with the SDK for wasabi.i3s.unice.fr

I guess that our best bet would be to add a constraint in DB and throw an exception in the worker when inserting a duplicate result in DB.

@yomguy Let us know if you have any thought.

**Comment by yomguy** [comment]
Hi @Tointoin 
Thx for the fix and the infos. 
To avoid any race condition and result duplication in the future, we may need to check the processors of all running task and and wait the task ends before running the new one. Then if any result exists for the same preset, it will not be re-run again.

**Pull request merged**
